menu:
    blog: /
    archive: /archives/
    open source: /open-source/
    about: /about/

favicon: /favicon.jpg
logo: /favicon.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2021
