menu:
  blog: /
  services: /services/
  about: /about/
  # FinTechNewz: https://t.me/FinTechNewz
  Donate: https://www.paypal.com/donate/?hosted_button_id=N8BZHR2P2SBEQ
  # archive: /archives/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: G-0EWRL1QZ6D

# Copyright Infomation
startyear: 2021
