menu:
  about: /
  blog: /blog/

favicon: /favicon.png
logo: /favicon.png

description: Игорь Костючёнок
# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: G-0EWRL1QZ6D

# Copyright Infomation
startyear: 2021
