menu:
  about: /
  blog: /blog/
  unstuck: https://t.me/unstuckme

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: G-0EWRL1QZ6D

# Copyright Infomation
startyear: 2021
